### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by lucadelu** [simone-f/wikipedia-tags-in-osm#24]
C'è la possibilità di aggiornare tutto a Python 3?

**Comment by CristianCantoro** [comment]
Seguo il thread (e ricordo che c'è questa PR aperta da un bel po', probabilmente un sacco di cose andrebbero aggiornate anche da quel lato)

**Comment by nico202** [comment]
Ciao,
il mio lavoro per portarlo a python3 è qui:
https://github.com/nico202/wikipedia-tags-in-osm/tree/2to3

tuttavia, la versione python2 mi fallisce.

```launch_script.py --print_categories_list```

nella versione del repo non funziona, la pagina wikipedia
https://en.wikipedia.org/wiki/Wikipedia:Quick_intersection
dice che è quick intersection stato rimpiazzato.

È possibile che sia online una versione diversa da questa?

**Comment by nico202** [comment]
Errore python 2:
```
  downloading data from Quick Intersection...
Traceback (most recent call last):
  File "launch_script.py", line 695, in <module>
    main()
  File "launch_script.py", line 692, in main
    App()
  File "launch_script.py", line 187, in __init__
    themesAndCatsNames = wikipedia_downloader.check_catscan_data(self, themesAndCatsNames)
  File "/home/nixo/git/wikipedia-tags-in-osm_python2/wikipedia_downloader.py", line 58, in check_catscan_data
    result = download_a_new_category(app, themeName, categoryName)
  File "/home/nixo/git/wikipedia-tags-in-osm_python2/wikipedia_downloader.py", line 88, in download_a_new_category
    data = urllib2.urlopen(request)
  File "/gnu/store/77p94z8zhx3iz4gmizwykwnhb3ip04dv-python2-2.7.17/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/gnu/store/77p94z8zhx3iz4gmizwykwnhb3ip04dv-python2-2.7.17/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/gnu/store/77p94z8zhx3iz4gmizwykwnhb3ip04dv-python2-2.7.17/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/gnu/store/77p94z8zhx3iz4gmizwykwnhb3ip04dv-python2-2.7.17/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/gnu/store/77p94z8zhx3iz4gmizwykwnhb3ip04dv-python2-2.7.17/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/gnu/store/77p94z8zhx3iz4gmizwykwnhb3ip04dv-python2-2.7.17/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 308: Permanent Redirect
```
